### ISSUE TITLE
Got crash on specific pgn file

### ISSUE THREAD

**Issue by ngoryachev** [dn1z/pgn2gif#11]
[Event "It"]
[Site "San Sebastian (Spain)"]
[Date "1911.??.??"]
[Round "6"]
[White "Tarrasch Siegbert (GER)"]
[Black "Rubinstein Akiba K (POL)"]
[Result "1/2-1/2"]
[WhiteElo "0"]
[BlackElo "0"]
[ECO "C10"]
[Annotator ""]
[Source ""]
[Remark ""]
[CurrentPosition " "]

1.e4 e6 2.d4 d5 3.Nc3 dxe4 4.Nxe4 Nd7 5.Nf3 Ngf6 6.Bd3 Be7 7.O-OO-O 8.Nxf6+ Nxf6 9.Ne5 c5 10.dxc5 Qc7 11.Qe2 Bxc5 12.Bg5 Nd7
13.Nxd7 Bxd7 14.Rad1 Bc6 15.Qh5 g6 16.Qh4 Rfe8 17.Rfe1 Be7 18.Bxe7
Qxe7 19.Qxe7 Rxe7 20.Be4 Rc8 21.c3 e5 22.Rd6 Bxe4 23.Rxe4 f5
24.Ra4 b6 25.g4 e4 26.gxf5 gxf5 27.Kf1 Kf7 28.Rad4 Re6 29.Rd7+
Re7 30.R4d5 Rxd7 31.Rxd7+ Kg6 32.Rxa7 Rd8 33.Ra6 Rd2 34.Rxb6+
Kg5 35.Ke1 Rc2 36.Rb5 Kg4 37.h3+ Kxh3 38.Rxf5 Rxb2 39.Rf4 Rxa2
40.Rxe4 h5 41.c4 Kg2 42.Rf4 Rc2 43.Rh4 Kf3 44.Kd1 Rxf2 45.c5
Ke3 46.Rxh5 Kd4 1/2-1/2

**Comment by ngoryachev** [comment]
I'm not true "pithonista" so cannot provide more context  ¯\_(ツ)_/¯

**Comment by dn1z** [comment]
Your pgn is not valid (7th move is 0-00-0 which is not a valid move). If you try to upload it to lichess or chess.com they will give you error messages, too.
