### ISSUE TITLE
Module 'pgn2gif' has no attribute 'PgnToGifCreator'

### ISSUE THREAD

**Issue by JiriKopriva** [dn1z/pgn2gif#13]
HI, thank you for your script. I have problem with this error. Please tell me where is problem?

Thank you

**Comment by JiriKopriva** [comment]
And when i try run with command line with pgn2gif -p 'MacKenzie.pgn' where is your example pgn, terminal sent me message: **AttributeError: 'Game' object has no attribute 'main_line'**

**Comment by dn1z** [comment]
This script do not have -p option or an object named Game or an attribute named main_line, so I think you are using someone else's script. Did you download script with pip? Because this repo has no pip entry. Or if you are using this one, please make sure that it is updated.

**Comment by JiriKopriva** [comment]
Thank you for quick reply. You are right. I installed pgn2gif by PyCharm from other developer. 
Now i installed your script.
Tell me please what mean positional argument? How can i add path to any directory if this is wrong:

pgn2gif -d 2 path '/home/desserter/PycharmProjects/Lichess/CarlsenGames/'

No such file or directory: 'path'

Thank you

**Comment by dn1z** [comment]
Hi again. Positional arguments mean you do not need to specify a flag (eg. pgn2gif game.pgn). As for your case, you can run `pgn2gif /home/desserter/PycharmProjects/Lichess/CarlsenGames/*.pgn`

**Comment by JiriKopriva** [comment]
Hi, thank for response, yeah this problem is solved. Thanks.
