### ISSUE TITLE
Use argparse or other command line parser 

### ISSUE THREAD

**Issue by mzfr** [dn1z/pgn2gif#2]
Currently this tool need pgn's to be present in a same folder in which the script but it would be nice if you can take path to pgn files/folder and then run the tool on them.

I would suggest to use [`argparse`](https://docs.python.org/3/library/argparse.html) for simplicity.

**Comment by dn1z** [comment]
Sorry for being late, I was in holiday.
Yes, It is more professional to use command line parser , but for the ease of use, I didn't add it and won't and probably.
Also thanks for care you showed my project.
