### ISSUE TITLE
Now working with Python 3.5.3 on Raspberry Pi

### ISSUE THREAD

**Issue by ScallyBag** [dn1z/pgn2gif#8]
Not an issue, just saying thanks.

Al.

**Comment by dn1z** [comment]
Hmm.. Can you post error message?

**Comment by ScallyBag** [comment]
Hi,

There is no issue or error. After your recent code change, your Pgn2gif program now works on Python 3.5.3. It didn’t work before as it needed Python 3.6 or higher.

I was just saying thank-you.

Al.

**Comment by dn1z** [comment]
Thank you, too.
